/**
 * Seed script for the 7 Flows Synergy database.
 * Populates the frameworks (4) and modes (29) tables.
 *
 * Run via: bunx wrangler d1 execute synergy-db --local --file=seed.sql
 * Or programmatically during development.
 */

import type { InferInsertModel } from 'drizzle-orm'
import { frameworks, modes } from './schema.js'

type FrameworkInsert = InferInsertModel<typeof frameworks>
type ModeInsert = InferInsertModel<typeof modes>

// ─── Frameworks ──────────────────────────────────────────────────────────────

export const frameworkSeeds: FrameworkInsert[] = [
  {
    id: 'fw-core',
    slug: 'core',
    name: 'Core X',
    description: 'Validation-driven business building. Test assumptions, build propositions, execute with evidence.',
    color: '#3B82F6',
    modeCount: 7,
  },
  {
    id: 'fw-air',
    slug: 'air',
    name: 'Air X',
    description: 'Flex work — async-first communication, distributed team coordination, remote culture.',
    color: '#14B8A6',
    modeCount: 7,
  },
  {
    id: 'fw-max',
    slug: 'max',
    name: 'Max X',
    description: 'Scaling 50-500 without bureaucracy. Org structure, cross-team connections, company priorities.',
    color: '#8B5CF6',
    modeCount: 8,
  },
  {
    id: 'fw-synergy',
    slug: 'synergy',
    name: 'Synergy X',
    description: 'Human-AI collaboration. Context sharing, delegation protocols, trust calibration.',
    color: '#F59E0B',
    modeCount: 7,
  },
]

// ─── Core X Modes (7) ────────────────────────────────────────────────────────

const coreModes: ModeInsert[] = [
  {
    id: 'mode-validation',
    frameworkId: 'fw-core',
    slug: 'validation',
    name: 'Validation Mode',
    purpose: 'Test your riskiest business assumption with evidence and make a clear Persevere/Pivot/Experiment Again decision.',
    trigger: 'Use when you are about to make a significant business decision based on something you believe but have not tested.',
    flowName: 'Validation',
    fieldsSchema: [
      { name: 'Assumption', description: 'The specific belief you are testing. Must be falsifiable.', type: 'textarea', required: true, example: 'Freelance designers will pay $49/month for automated invoicing.' },
      { name: 'Risk Level', description: 'How much damage if this assumption is wrong.', type: 'select', required: true, options: ['High', 'Medium', 'Low'] },
      { name: 'Current Evidence', description: 'What you already know. Data, conversations, signals.', type: 'textarea', required: true },
      { name: 'Experiment Design', description: 'The cheapest, fastest test that could disprove the assumption.', type: 'textarea', required: true },
      { name: 'Success Criteria', description: 'The specific number that means the assumption holds.', type: 'text', required: true, example: '5% sign-up rate within 7 days.' },
      { name: 'Time Box', description: 'How long the experiment runs.', type: 'text', required: true, example: '7 days.' },
      { name: 'Results', description: 'What actually happened. Raw data, not interpretation.', type: 'textarea', required: true },
      { name: 'Decision', description: 'Based on the evidence: Persevere, Pivot, or Experiment Again.', type: 'select', required: true, options: ['Persevere', 'Pivot', 'Experiment Again'] },
      { name: 'Next Action', description: 'The specific next step with a date.', type: 'text', required: true },
      { name: 'Assumption Update', description: 'How has this assumption changed based on what you learned?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Is this assumption specific enough to disprove? Can you name the exact evidence that would make you abandon it?' },
      { fieldIndex: 3, prompt: 'What is the cheapest version of this test? Can you get a signal in 48 hours instead of 2 weeks?' },
      { fieldIndex: 4, prompt: 'Is this criteria binary? Will you actually pivot if the number comes in below this threshold?' },
      { fieldIndex: 6, prompt: 'Are you interpreting or reporting? Strip the story. What do the numbers say?' },
      { fieldIndex: 7, prompt: 'Is this decision driven by the evidence or by what you want to be true?' },
    ],
    doneSignal: 'Can you state your assumption, the evidence for or against it, and your decision in one sentence?',
    metricsSchema: [
      { name: 'assumptions_tested', unit: 'count', extraction: 'Increment by 1 on session completion' },
      { name: 'test_to_decision_time', unit: 'days', extraction: 'Days from session start to completion' },
      { name: 'pivot_rate', unit: 'percentage', extraction: 'Percentage of decisions that are Pivot' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'business-engine', description: 'Assumptions identified in Business Engine feed into Validation' },
      { direction: 'receives_from', modeSlug: 'priority-stack', description: 'Highest-priority assumption from Priority Stack' },
      { direction: 'feeds_into', modeSlug: 'insight-capture', description: 'Experiment results feed into Insight Capture' },
      { direction: 'feeds_into', modeSlug: 'package', description: 'Validated results can be packaged for team review' },
    ],
    timeEstimateMinutes: 20,
    sortOrder: 1,
  },
  {
    id: 'mode-insight-capture',
    frameworkId: 'fw-core',
    slug: 'insight-capture',
    name: 'Insight Capture Mode',
    purpose: 'Turn raw signals from your market into structured patterns and actionable next steps.',
    trigger: 'Use when you have raw data, customer conversations, or market signals that need structure.',
    flowName: 'Validation',
    fieldsSchema: [
      { name: 'Signal Source', description: 'Where did this insight come from?', type: 'select', required: true, options: ['Customer conversation', 'Usage data', 'Market research', 'Competitor observation', 'Team feedback', 'Other'] },
      { name: 'Raw Signal', description: 'The exact observation, quote, or data point.', type: 'textarea', required: true },
      { name: 'Pattern Match', description: 'Does this connect to anything you have seen before?', type: 'textarea', required: true },
      { name: 'Strength', description: 'How strong is this signal?', type: 'select', required: true, options: ['Strong (multiple sources)', 'Moderate (2+ signals)', 'Weak (single signal)'] },
      { name: 'Implication', description: 'If this signal is real, what does it mean for your business?', type: 'textarea', required: true },
      { name: 'Action', description: 'What specific next step does this insight drive?', type: 'text', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 1, prompt: 'Is this a fact or your interpretation of a fact? Separate them.' },
      { fieldIndex: 2, prompt: 'How many independent signals point to this same pattern? One is noise, three is a trend.' },
      { fieldIndex: 4, prompt: 'What would you do differently tomorrow if this implication is true?' },
    ],
    doneSignal: 'Can you explain this insight to someone who was not in the room, with enough context for them to act on it?',
    metricsSchema: [
      { name: 'insights_captured', unit: 'count', extraction: 'Increment by 1 on session completion' },
      { name: 'evidence_freshness', unit: 'days', extraction: 'Age of most recent evidence referenced' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'validation', description: 'Experiment results feed into Insight Capture' },
      { direction: 'feeds_into', modeSlug: 'proposition-builder', description: 'Validated insights inform value propositions' },
    ],
    timeEstimateMinutes: 15,
    sortOrder: 2,
  },
  {
    id: 'mode-proposition-builder',
    frameworkId: 'fw-core',
    slug: 'proposition-builder',
    name: 'Proposition Builder Mode',
    purpose: 'Build evidence-backed value propositions in three tiers: Basic, Satisfier, Delighter.',
    trigger: 'Use when you need to articulate what you offer and why it matters, grounded in evidence.',
    flowName: 'Validation',
    fieldsSchema: [
      { name: 'Target Customer', description: 'Who exactly is this proposition for?', type: 'textarea', required: true },
      { name: 'Problem Statement', description: 'The specific problem you are solving, in their words.', type: 'textarea', required: true },
      { name: 'Basic Tier', description: 'The minimum viable value — what you must deliver.', type: 'textarea', required: true },
      { name: 'Satisfier Tier', description: 'Expected value that meets the standard.', type: 'textarea', required: true },
      { name: 'Delighter Tier', description: 'Unexpected value that creates loyalty.', type: 'textarea', required: true },
      { name: 'Evidence', description: 'What validated data supports each tier?', type: 'textarea', required: true },
      { name: 'Differentiation', description: 'What makes your proposition different from alternatives?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Can you name three real people who fit this description? If not, it is too vague.' },
      { fieldIndex: 2, prompt: 'Would you buy this? Would you tell a friend about it? Be honest.' },
      { fieldIndex: 5, prompt: 'How much of this evidence is from actual customers vs your own assumptions?' },
    ],
    doneSignal: 'Can a new team member explain your value proposition in 30 seconds, including who it is for and why they care?',
    metricsSchema: [
      { name: 'proposition_clarity', unit: 'score', extraction: 'Self-rated 1-10 on completion' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'insight-capture', description: 'Validated insights inform propositions' },
      { direction: 'feeds_into', modeSlug: 'business-engine', description: 'Proposition feeds into business model design' },
    ],
    timeEstimateMinutes: 20,
    sortOrder: 3,
  },
  {
    id: 'mode-business-engine',
    frameworkId: 'fw-core',
    slug: 'business-engine',
    name: 'Business Engine Mode',
    purpose: 'Map your business model assumptions and identify which ones could break the engine.',
    trigger: 'Use when you need to understand how your business works as a system and which assumptions are load-bearing.',
    flowName: 'Strategy',
    fieldsSchema: [
      { name: 'Revenue Model', description: 'How does money come in? Be specific about pricing and channels.', type: 'textarea', required: true },
      { name: 'Cost Structure', description: 'Where does money go? Fixed vs variable costs.', type: 'textarea', required: true },
      { name: 'Key Assumptions', description: 'List the 3-5 assumptions your model depends on.', type: 'textarea', required: true },
      { name: 'Riskiest Assumption', description: 'Which assumption, if wrong, breaks the model?', type: 'text', required: true },
      { name: 'Current Evidence', description: 'What data supports or challenges each assumption?', type: 'textarea', required: true },
      { name: 'Unit Economics', description: 'Revenue per unit, cost per unit, margin.', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Are these really assumptions or are they facts? An assumption is something that could be wrong.' },
      { fieldIndex: 3, prompt: 'If this assumption fails, does the business survive? Or does everything unravel?' },
      { fieldIndex: 5, prompt: 'Do these numbers come from data or from your spreadsheet fantasy? There is a difference.' },
    ],
    doneSignal: 'Can you explain your business model in one sentence, name the riskiest assumption, and say what evidence you have for it?',
    metricsSchema: [
      { name: 'assumptions_identified', unit: 'count', extraction: 'Count of key assumptions listed' },
    ],
    composabilityHooks: [
      { direction: 'feeds_into', modeSlug: 'priority-stack', description: 'Assumptions feed into priority ranking' },
      { direction: 'feeds_into', modeSlug: 'validation', description: 'Riskiest assumption should be validated' },
    ],
    timeEstimateMinutes: 25,
    sortOrder: 4,
  },
  {
    id: 'mode-priority-stack',
    frameworkId: 'fw-core',
    slug: 'priority-stack',
    name: 'Priority Stack Mode',
    purpose: 'Create an evidence-based forced ranking of priorities with a clear Not Doing list.',
    trigger: 'Use when you have more things to do than time to do them, and need ruthless clarity on what matters.',
    flowName: 'Strategy',
    fieldsSchema: [
      { name: 'Candidates', description: 'List everything competing for your attention right now.', type: 'textarea', required: true },
      { name: 'Criteria', description: 'What criteria will you use to rank? Impact, urgency, evidence strength.', type: 'textarea', required: true },
      { name: 'Forced Rank', description: 'Rank all candidates 1 to N. No ties allowed.', type: 'textarea', required: true },
      { name: 'Top 3', description: 'Your top 3 priorities with one-sentence justification each.', type: 'textarea', required: true },
      { name: 'Not Doing List', description: 'Everything below the cut line. Say it explicitly.', type: 'textarea', required: true },
      { name: 'Time Allocation', description: 'How will your time split across the top 3 this period?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Are you ranking by evidence or by emotion? Which of these priorities has the strongest data behind it?' },
      { fieldIndex: 4, prompt: 'Is the Not Doing list honest? Or did you sneak in a maybe?' },
    ],
    doneSignal: 'Can you tell someone your top 3 priorities and your Not Doing list without hesitation?',
    metricsSchema: [
      { name: 'priority_alignment', unit: 'percentage', extraction: 'Active work connected to stated priorities' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'business-engine', description: 'Assumptions from Business Engine need ranking' },
      { direction: 'feeds_into', modeSlug: 'execution-tracker', description: 'Top priorities feed into execution tracking' },
      { direction: 'feeds_into', modeSlug: 'validation', description: 'Highest-priority assumption goes to Validation' },
    ],
    timeEstimateMinutes: 15,
    sortOrder: 5,
  },
  {
    id: 'mode-execution-tracker',
    frameworkId: 'fw-core',
    slug: 'execution-tracker',
    name: 'Execution Tracker Mode',
    purpose: 'Track work visibility and identify blockers with async-first status tracking.',
    trigger: 'Use when you need to see what is happening, what is stuck, and what needs unblocking.',
    flowName: 'Execution',
    fieldsSchema: [
      { name: 'Work Items', description: 'List active work items connected to your priorities.', type: 'textarea', required: true },
      { name: 'Status', description: 'For each item: Not Started, In Progress, Blocked, Done.', type: 'textarea', required: true },
      { name: 'Blockers', description: 'What is blocked and why? Be specific.', type: 'textarea', required: true },
      { name: 'Unblock Actions', description: 'For each blocker: who needs to do what by when?', type: 'textarea', required: true },
      { name: 'Cycle Time', description: 'How long from start to completion for recent items?', type: 'text', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'How long has this been blocked? If more than 3 days, the unblock action is not aggressive enough.' },
      { fieldIndex: 4, prompt: 'Is your cycle time improving or declining? What changed?' },
    ],
    doneSignal: 'Can you see all active work, know what is blocked, and have a specific unblock action for each blocker?',
    metricsSchema: [
      { name: 'cycle_time', unit: 'days', extraction: 'Average days from start to completion' },
      { name: 'blocked_time', unit: 'hours', extraction: 'Hours items spent in Blocked status' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'priority-stack', description: 'Priorities define what to track' },
      { direction: 'feeds_into', modeSlug: 'delivery-check', description: 'Completed items go to Delivery Check' },
    ],
    timeEstimateMinutes: 15,
    sortOrder: 6,
  },
  {
    id: 'mode-delivery-check',
    frameworkId: 'fw-core',
    slug: 'delivery-check',
    name: 'Delivery Check Mode',
    purpose: 'Quality-gate completed work and monitor post-delivery performance.',
    trigger: 'Use when work is done and needs a quality check before calling it shipped.',
    flowName: 'Execution',
    fieldsSchema: [
      { name: 'Deliverable', description: 'What was delivered? Be specific.', type: 'text', required: true },
      { name: 'Quality Criteria', description: 'What standards must it meet?', type: 'textarea', required: true },
      { name: 'Quality Assessment', description: 'Does it meet each criterion? Pass/Fail per item.', type: 'textarea', required: true },
      { name: 'Issues Found', description: 'What needs fixing before ship?', type: 'textarea', required: false },
      { name: 'Post-Ship Monitoring', description: 'What will you watch after delivery to confirm quality?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Are you being honest with yourself? Would a customer agree this meets the standard?' },
      { fieldIndex: 4, prompt: 'How long will you monitor? What number would make you pull it back?' },
    ],
    doneSignal: 'Can you confidently say this deliverable is ready for the person who receives it?',
    metricsSchema: [
      { name: 'delivery_throughput', unit: 'count', extraction: 'Completed delivery checks per period' },
      { name: 'quality_pass_rate', unit: 'percentage', extraction: 'First-pass quality rate' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'execution-tracker', description: 'Completed work items from Execution Tracker' },
    ],
    timeEstimateMinutes: 10,
    sortOrder: 7,
  },
]

// ─── Air X Modes (7) ─────────────────────────────────────────────────────────

const airModes: ModeInsert[] = [
  {
    id: 'mode-information-architecture',
    frameworkId: 'fw-air',
    slug: 'information-architecture',
    name: 'Information Architecture Mode',
    purpose: 'Design where information lives so people can find what they need in 5 minutes without asking.',
    trigger: 'Use when people keep asking where things are, information is duplicated or lost, or new joiners cannot find what they need.',
    flowName: 'Inform',
    fieldsSchema: [
      { name: 'Information Audit', description: 'Where does information currently live? List all tools and locations.', type: 'textarea', required: true },
      { name: 'Pain Points', description: 'What information is hardest to find? What questions get asked repeatedly?', type: 'textarea', required: true },
      { name: 'Categories', description: 'Group information into logical categories.', type: 'textarea', required: true },
      { name: 'Single Source of Truth', description: 'For each category, where is the canonical location?', type: 'textarea', required: true },
      { name: 'Findability Test', description: 'Can a new team member find X in 5 minutes? Test 3 common items.', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'How many tools are you using? More than 5 is a red flag. Information gets lost in the gaps.' },
      { fieldIndex: 4, prompt: 'Did you actually test this with someone, or are you assuming it works because you know where everything is?' },
    ],
    doneSignal: 'Can a new team member find any piece of critical information in 5 minutes without asking someone?',
    metricsSchema: [
      { name: 'findability_score', unit: 'percentage', extraction: 'Percentage of items found within 5 minutes in test' },
    ],
    composabilityHooks: [
      { direction: 'feeds_into', modeSlug: 'flex-work-design', description: 'Information structure enables async work design' },
      { direction: 'feeds_into', modeSlug: 'knowledge-architecture', description: 'Information categories feed AI knowledge structure' },
    ],
    timeEstimateMinutes: 20,
    sortOrder: 1,
  },
  {
    id: 'mode-flex-work-design',
    frameworkId: 'fw-air',
    slug: 'flex-work-design',
    name: 'Flex Work Design Mode',
    purpose: 'Define async defaults, sync exceptions, meeting budget, and energy rhythms for your team.',
    trigger: 'Use when your team is spending too much time in meetings, working across time zones, or struggling with work-life boundaries.',
    flowName: 'Inform',
    fieldsSchema: [
      { name: 'Current Meeting Load', description: 'How many hours per week does each person spend in meetings?', type: 'text', required: true },
      { name: 'Async Default', description: 'What is your default: async or sync? Define the rule.', type: 'textarea', required: true },
      { name: 'Sync Exceptions', description: 'What specifically requires real-time interaction?', type: 'textarea', required: true },
      { name: 'Meeting Budget', description: 'Maximum meeting hours per person per week.', type: 'text', required: true },
      { name: 'Energy Rhythms', description: 'When are people most productive? How do you protect deep work?', type: 'textarea', required: true },
      { name: 'Time Zone Protocol', description: 'How do you handle async across zones? Core overlap hours?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'That is a lot of meetings. Which ones would the team cancel tomorrow if they could?' },
      { fieldIndex: 3, prompt: 'Is this budget enforced or aspirational? Who has authority to say no to a meeting?' },
    ],
    doneSignal: 'Can every team member explain when to default to async, when sync is appropriate, and what their meeting budget is?',
    metricsSchema: [
      { name: 'meeting_hours', unit: 'hours', extraction: 'Meeting hours per person per week' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'information-architecture', description: 'Information structure enables flex work' },
      { direction: 'feeds_into', modeSlug: 'team-rhythm', description: 'Work design feeds into team cadence' },
    ],
    timeEstimateMinutes: 20,
    sortOrder: 2,
  },
  {
    id: 'mode-team-rhythm',
    frameworkId: 'fw-air',
    slug: 'team-rhythm',
    name: 'Team Rhythm Mode',
    purpose: 'Design your weekly cadence: sync touchpoints, deep work blocks, energy checkpoints.',
    trigger: 'Use when the team lacks a consistent cadence, people do not know when to expect updates, or deep work keeps getting interrupted.',
    flowName: 'Coordinate',
    fieldsSchema: [
      { name: 'Weekly Cadence', description: 'Map out the recurring weekly rhythm for the team.', type: 'textarea', required: true },
      { name: 'Sync Touchpoints', description: 'List the essential sync moments and their purpose.', type: 'textarea', required: true },
      { name: 'Deep Work Blocks', description: 'When are protected focus periods? How are they enforced?', type: 'textarea', required: true },
      { name: 'Energy Checkpoints', description: 'How do you check team energy and workload?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 1, prompt: 'Does each sync touchpoint have a clear purpose? If you cannot state it in one sentence, it might be a meeting that should be async.' },
    ],
    doneSignal: 'Does every team member know the weekly rhythm without checking a calendar?',
    metricsSchema: [
      { name: 'meeting_hours_per_person', unit: 'hours', extraction: 'Weekly meeting hours per person' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'flex-work-design', description: 'Work design defines rhythm constraints' },
      { direction: 'feeds_into', modeSlug: 'async-decision', description: 'Rhythm defines when decisions happen async vs sync' },
    ],
    timeEstimateMinutes: 15,
    sortOrder: 3,
  },
  {
    id: 'mode-async-decision',
    frameworkId: 'fw-air',
    slug: 'async-decision',
    name: 'Async Decision Mode',
    purpose: 'Make a clear decision asynchronously with structured question, options, deadline, and dissent protocol.',
    trigger: 'Use when a decision needs to be made and a meeting is not the best way to make it.',
    flowName: 'Coordinate',
    fieldsSchema: [
      { name: 'Decision Question', description: 'The specific question being decided. One sentence.', type: 'text', required: true },
      { name: 'Options', description: 'The options being considered, with pros/cons for each.', type: 'textarea', required: true },
      { name: 'Decision Maker', description: 'Who makes the final call?', type: 'text', required: true },
      { name: 'Deadline', description: 'When must the decision be made?', type: 'text', required: true },
      { name: 'Input Requested From', description: 'Who needs to weigh in before the deadline?', type: 'textarea', required: true },
      { name: 'Dissent Protocol', description: 'How can someone disagree? What happens with objections?', type: 'textarea', required: true },
      { name: 'Decision Record', description: 'The final decision, rationale, and who was consulted.', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Is this actually one decision or are there two decisions tangled together? Separate them.' },
      { fieldIndex: 5, prompt: 'Silence is not consent. How will you know if someone disagrees but did not speak up?' },
    ],
    doneSignal: 'Is the decision recorded, rationale documented, and all stakeholders notified?',
    metricsSchema: [
      { name: 'async_decision_rate', unit: 'percentage', extraction: 'Async decisions vs total decisions' },
    ],
    composabilityHooks: [
      { direction: 'feeds_into', modeSlug: 'package', description: 'Decisions should be packaged for team visibility' },
    ],
    timeEstimateMinutes: 15,
    sortOrder: 4,
  },
  {
    id: 'mode-package',
    frameworkId: 'fw-air',
    slug: 'package',
    name: 'Package Mode',
    purpose: 'Create self-contained communication packages that do not require follow-up questions.',
    trigger: 'Use when sharing work, updates, or decisions with people who were not in the room.',
    flowName: 'Communicate',
    fieldsSchema: [
      { name: 'Context', description: 'What does the reader need to know to understand this?', type: 'textarea', required: true },
      { name: 'Key Points', description: 'The 3-5 most important things. Numbered.', type: 'textarea', required: true },
      { name: 'Decision Needed', description: 'Is a decision needed? From whom? By when?', type: 'textarea', required: false },
      { name: 'Deadline', description: 'When does the reader need to respond?', type: 'text', required: false },
      { name: 'Feedback Format', description: 'How should the reader respond? Comment, approve, edit?', type: 'text', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Can someone who missed the last 2 weeks understand this package without asking you a question?' },
      { fieldIndex: 1, prompt: 'Are these really the key points, or are you burying the lead? What is the one thing they must know?' },
    ],
    doneSignal: 'Can someone act on this package without asking a single clarifying question?',
    metricsSchema: [
      { name: 'package_clarity', unit: 'percentage', extraction: 'Packages without clarifying questions' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'validation', description: 'Validation results can be packaged' },
      { direction: 'receives_from', modeSlug: 'async-decision', description: 'Decisions should be packaged' },
    ],
    timeEstimateMinutes: 10,
    sortOrder: 5,
  },
  {
    id: 'mode-contribution-tracker',
    frameworkId: 'fw-air',
    slug: 'contribution-tracker',
    name: 'Contribution Tracker Mode',
    purpose: 'Make invisible work visible across 5 contribution types.',
    trigger: 'Use when some team members do critical work that nobody sees, or recognition is skewed toward visible deliverables.',
    flowName: 'Recognize',
    fieldsSchema: [
      { name: 'Team Member', description: 'Who are you tracking contributions for?', type: 'text', required: true },
      { name: 'Delivery', description: 'Tangible outputs shipped.', type: 'textarea', required: true },
      { name: 'Mentoring', description: 'Helping others grow, pairing, reviewing, teaching.', type: 'textarea', required: true },
      { name: 'Documentation', description: 'Writing that helps others work independently.', type: 'textarea', required: true },
      { name: 'Process Improvement', description: 'Making systems, tools, or workflows better.', type: 'textarea', required: true },
      { name: 'Unblocking', description: 'Removing obstacles for others.', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Mentoring is often invisible. Who helped someone this week that nobody noticed?' },
      { fieldIndex: 5, prompt: 'Unblocking is the most underrated contribution type. Who cleared the path for someone else?' },
    ],
    doneSignal: 'Can you see contributions across all 5 types, not just delivery?',
    metricsSchema: [
      { name: 'contribution_diversity', unit: 'score', extraction: 'Distribution across 5 contribution types' },
      { name: 'recognition_rate', unit: 'count', extraction: 'Recognition events per person per period' },
    ],
    composabilityHooks: [],
    timeEstimateMinutes: 15,
    sortOrder: 6,
  },
  {
    id: 'mode-culture-at-distance',
    frameworkId: 'fw-air',
    slug: 'culture-at-distance',
    name: 'Culture at Distance Mode',
    purpose: 'Define observable behaviors, rituals, conflict protocol, and trust signals for distributed teams.',
    trigger: 'Use when culture feels thin in a distributed team — people are productive but disconnected.',
    flowName: 'Culture',
    fieldsSchema: [
      { name: 'Observable Behaviors', description: 'What behaviors define your culture? List 5 that are visible in async work.', type: 'textarea', required: true },
      { name: 'Rituals', description: 'Regular practices that reinforce culture. Not meetings — rituals.', type: 'textarea', required: true },
      { name: 'Conflict Protocol', description: 'How do you handle disagreements when you cannot read body language?', type: 'textarea', required: true },
      { name: 'Trust Signals', description: 'What builds trust in your distributed team? What erodes it?', type: 'textarea', required: true },
      { name: 'Anti-Patterns', description: 'What behaviors are you actively trying to prevent?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Can someone observe these behaviors in Slack messages and pull requests? If not, they are aspirational, not real.' },
      { fieldIndex: 2, prompt: 'What happens when someone violates this protocol? If there are no consequences, it is not a protocol.' },
    ],
    doneSignal: 'Could a new remote hire understand your team culture from documentation alone?',
    metricsSchema: [],
    composabilityHooks: [],
    timeEstimateMinutes: 20,
    sortOrder: 7,
  },
]

// ─── Max X Modes (8) ─────────────────────────────────────────────────────────

const maxModes: ModeInsert[] = [
  {
    id: 'mode-dashboard', frameworkId: 'fw-max', slug: 'dashboard', name: 'Dashboard Mode',
    purpose: 'Set up dual metrics: performance (resolution time, cycle time) and dynamics (learning, collaboration, fun).',
    trigger: 'Use when scaling past 50 people and traditional metrics miss the human side of the organization.',
    flowName: 'Monitor',
    fieldsSchema: [
      { name: 'Performance Metrics', description: 'Key operational metrics: cycle time, resolution time, lead time.', type: 'textarea', required: true },
      { name: 'Dynamics Metrics', description: 'Human metrics: learning rate, collaboration score, commitment, fun.', type: 'textarea', required: true },
      { name: 'Data Sources', description: 'Where does each metric come from?', type: 'textarea', required: true },
      { name: 'Review Cadence', description: 'How often are these reviewed and by whom?', type: 'text', required: true },
      { name: 'Action Triggers', description: 'What metric levels trigger action?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 1, prompt: 'Are you measuring what matters to people, or what is easy to measure? Fun sounds soft but predicts retention.' },
    ],
    doneSignal: 'Can you see both performance and dynamics at a glance, and know when to act?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'feeds_into', modeSlug: 'org-map', description: 'Dashboard signals feed into org structure review' }],
    timeEstimateMinutes: 25, sortOrder: 1,
  },
  {
    id: 'mode-org-map', frameworkId: 'fw-max', slug: 'org-map', name: 'Org Map Mode',
    purpose: 'Create a bird\'s-eye view of your organization: team types, gaps, and overlaps.',
    trigger: 'Use when the organization is growing and you need to see the whole picture.',
    flowName: 'Structure',
    fieldsSchema: [
      { name: 'Teams', description: 'List all teams with type: Mission, Platform, or Leadership Circle.', type: 'textarea', required: true },
      { name: 'Team Sizes', description: 'Head count per team.', type: 'textarea', required: true },
      { name: 'Gaps', description: 'What capabilities are missing?', type: 'textarea', required: true },
      { name: 'Overlaps', description: 'Where are teams duplicating effort?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Gaps are strategic choices. Are these intentional gaps or blind spots?' },
    ],
    doneSignal: 'Can you explain your org structure to a new VP in 5 minutes?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'feeds_into', modeSlug: 'team-blueprint', description: 'Org map identifies teams needing blueprints' }],
    timeEstimateMinutes: 20, sortOrder: 2,
  },
  {
    id: 'mode-team-blueprint', frameworkId: 'fw-max', slug: 'team-blueprint', name: 'Team Blueprint Mode',
    purpose: 'Define mission, members, decision authority, cadence, and quality standards for a team.',
    trigger: 'Use when creating a new team or when an existing team lacks clarity on its purpose and authority.',
    flowName: 'Structure',
    fieldsSchema: [
      { name: 'Team Mission', description: 'Why does this team exist? One sentence.', type: 'text', required: true },
      { name: 'Members', description: 'Who is on the team and what are their roles?', type: 'textarea', required: true },
      { name: 'Decision Authority', description: 'What decisions can this team make without escalation?', type: 'textarea', required: true },
      { name: 'Cadence', description: 'How does the team communicate and coordinate?', type: 'textarea', required: true },
      { name: 'Quality Standards', description: 'What quality bar does this team maintain?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'If you removed this team, who would notice first and why? That is your mission.' },
      { fieldIndex: 2, prompt: 'Is there anything this team thinks it can decide but actually cannot? That ambiguity will bite you.' },
    ],
    doneSignal: 'Can every team member state the mission, their role, and what decisions they can make?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'feeds_into', modeSlug: 'connection-map', description: 'Team blueprints define nodes in the connection map' }],
    timeEstimateMinutes: 20, sortOrder: 3,
  },
  {
    id: 'mode-connection-map', frameworkId: 'fw-max', slug: 'connection-map', name: 'Connection Map Mode',
    purpose: 'Map team interactions: smooth, friction, or broken. Find bottlenecks.',
    trigger: 'Use when cross-team coordination is slow, handoffs drop, or teams blame each other.',
    flowName: 'Connect',
    fieldsSchema: [
      { name: 'Team Pairs', description: 'List all team-to-team interaction pairs.', type: 'textarea', required: true },
      { name: 'Interaction Quality', description: 'For each pair: Smooth, Friction, or Broken.', type: 'textarea', required: true },
      { name: 'Bottlenecks', description: 'Which team pairs are the biggest bottlenecks?', type: 'textarea', required: true },
      { name: 'Root Causes', description: 'Why is each bottleneck stuck?', type: 'textarea', required: true },
      { name: 'Fix Actions', description: 'What specific action will improve each bottleneck?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Are these bottlenecks people problems or process problems? The fix is different.' },
    ],
    doneSignal: 'Can you show someone a map of all team connections with quality ratings and bottleneck fixes?',
    metricsSchema: [
      { name: 'connection_coverage', unit: 'percentage', extraction: 'Team pairs with defined interactions' },
      { name: 'bottleneck_count', unit: 'count', extraction: 'Number of Friction or Broken connections' },
    ],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'team-blueprint', description: 'Blueprints define the teams to map' },
      { direction: 'feeds_into', modeSlug: 'relationship-health', description: 'Problem connections need health diagnosis' },
    ],
    timeEstimateMinutes: 25, sortOrder: 4,
  },
  {
    id: 'mode-relationship-health', frameworkId: 'fw-max', slug: 'relationship-health', name: 'Relationship Health Mode',
    purpose: 'Diagnose and fix inter-team friction with structured analysis.',
    trigger: 'Use when two teams have a Friction or Broken connection that needs repair.',
    flowName: 'Connect',
    fieldsSchema: [
      { name: 'Teams Involved', description: 'Which two teams have the friction?', type: 'text', required: true },
      { name: 'Pain Generators', description: 'What specific actions or inactions cause pain?', type: 'textarea', required: true },
      { name: 'Expectations Gap', description: 'What does each team expect from the other? Where do expectations differ?', type: 'textarea', required: true },
      { name: 'Value Proposition', description: 'What value does each team provide to the other?', type: 'textarea', required: true },
      { name: 'Fix Protocol', description: 'Agreed actions to improve the relationship.', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 1, prompt: 'Are you describing symptoms or root causes? "Slow responses" is a symptom. Why are they slow?' },
    ],
    doneSignal: 'Have both teams agreed on the fix protocol and committed to a review date?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'receives_from', modeSlug: 'connection-map', description: 'Problem connections identified in Connection Map' }],
    timeEstimateMinutes: 20, sortOrder: 5,
  },
  {
    id: 'mode-company-priority', frameworkId: 'fw-max', slug: 'company-priority', name: 'Company Priority Mode',
    purpose: 'Align 3-5 company priorities with evidence, team translation, and dependency mapping.',
    trigger: 'Use when the company has too many priorities, teams are pulling in different directions, or quarterly planning is needed.',
    flowName: 'Align',
    fieldsSchema: [
      { name: 'Company Priorities', description: 'List 3-5 company priorities with evidence basis.', type: 'textarea', required: true },
      { name: 'Team Translation', description: 'What does each priority mean for each team?', type: 'textarea', required: true },
      { name: 'Dependencies', description: 'Which priorities depend on which teams?', type: 'textarea', required: true },
      { name: 'Conflict Resolution', description: 'When priorities conflict, which wins?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'More than 5 priorities means no priorities. Which of these would you cut if you had to?' },
    ],
    doneSignal: 'Can every team lead explain company priorities and how their team contributes?',
    metricsSchema: [{ name: 'priority_alignment_cross_team', unit: 'percentage', extraction: 'Teams aligned to stated priorities' }],
    composabilityHooks: [{ direction: 'feeds_into', modeSlug: 'scaled-execution', description: 'Priorities drive execution tracking at scale' }],
    timeEstimateMinutes: 25, sortOrder: 6,
  },
  {
    id: 'mode-scaled-execution', frameworkId: 'fw-max', slug: 'scaled-execution', name: 'Scaled Execution Mode',
    purpose: 'Track cross-team execution with priority connections, key deliverables, and dependencies.',
    trigger: 'Use when multiple teams are working toward the same priorities and need visibility into each other\'s progress.',
    flowName: 'Execute',
    fieldsSchema: [
      { name: 'Priority Connection', description: 'Which company priority does this work connect to?', type: 'text', required: true },
      { name: 'Key Deliverables', description: 'What must be delivered and by which team?', type: 'textarea', required: true },
      { name: 'Cross-Team Dependencies', description: 'Which teams depend on which deliverables?', type: 'textarea', required: true },
      { name: 'Status', description: 'Current status of each deliverable.', type: 'textarea', required: true },
      { name: 'Blockers', description: 'Cross-team blockers and unblock actions.', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Dependencies are where scaled execution breaks. Who is waiting on whom? Is it explicit?' },
    ],
    doneSignal: 'Can you see all cross-team work, dependencies, and blockers in one view?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'receives_from', modeSlug: 'company-priority', description: 'Priorities define what to track at scale' }],
    timeEstimateMinutes: 20, sortOrder: 7,
  },
  {
    id: 'mode-quality-matrix', frameworkId: 'fw-max', slug: 'quality-matrix', name: 'Quality Matrix Mode',
    purpose: 'Define consistent quality standards across teams: company-wide plus team-specific.',
    trigger: 'Use when quality varies across teams and there is no shared definition of "good enough."',
    flowName: 'Quality',
    fieldsSchema: [
      { name: 'Company-Wide Standards', description: 'Quality standards that apply to every team.', type: 'textarea', required: true },
      { name: 'Team-Specific Standards', description: 'Standards unique to each team based on their domain.', type: 'textarea', required: true },
      { name: 'Measurement', description: 'How is quality measured for each standard?', type: 'textarea', required: true },
      { name: 'Review Process', description: 'Who reviews quality and how often?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Are these standards clear enough that two people would independently agree on pass/fail?' },
    ],
    doneSignal: 'Can any team member look up the quality standard for their work and know if they meet it?',
    metricsSchema: [{ name: 'quality_consistency', unit: 'score', extraction: 'Cross-team quality variance' }],
    composabilityHooks: [],
    timeEstimateMinutes: 20, sortOrder: 8,
  },
]

// ─── Synergy X Modes (7) ─────────────────────────────────────────────────────

const synergyModes: ModeInsert[] = [
  {
    id: 'mode-ai-onboarding', frameworkId: 'fw-synergy', slug: 'ai-onboarding', name: 'AI Colleague Onboarding Mode',
    purpose: 'Define AI colleague roles, knowledge sources, access boundaries, and success metrics.',
    trigger: 'Use when starting to work with AI tools and you need to set up the collaboration properly.',
    flowName: 'Context',
    fieldsSchema: [
      { name: 'AI Role', description: 'What role does the AI play in your workflow?', type: 'textarea', required: true },
      { name: 'Knowledge Sources', description: 'What information does the AI need access to?', type: 'textarea', required: true },
      { name: 'Access Boundaries', description: 'What should the AI NOT have access to?', type: 'textarea', required: true },
      { name: 'Success Metrics', description: 'How will you measure if the AI collaboration is working?', type: 'textarea', required: true },
      { name: 'Review Cadence', description: 'How often will you review the AI collaboration setup?', type: 'text', required: true },
      { name: 'Escalation Triggers', description: 'When should a human take over from the AI?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Is this a tool role or a colleague role? The setup is different. Tools you use when needed. Colleagues participate proactively.' },
      { fieldIndex: 3, prompt: 'Are you measuring output quality or just output quantity? An AI that produces a lot of mediocre work is worse than no AI.' },
    ],
    doneSignal: 'Could you hand this onboarding document to a new team member and they would know exactly how your team uses AI?',
    metricsSchema: [{ name: 'ai_context_completeness', unit: 'percentage', extraction: 'Coverage of AI knowledge domains' }],
    composabilityHooks: [{ direction: 'feeds_into', modeSlug: 'centaur-assessment', description: 'AI setup feeds into task delegation assessment' }],
    timeEstimateMinutes: 20, sortOrder: 1,
  },
  {
    id: 'mode-centaur-assessment', frameworkId: 'fw-synergy', slug: 'centaur-assessment', name: 'Centaur Assessment Mode',
    purpose: 'Map every task: human-led, AI-led, or centaur (both) with capability assessment.',
    trigger: 'Use when you need to decide which tasks AI can handle and which need human judgment.',
    flowName: 'Context',
    fieldsSchema: [
      { name: 'Task Inventory', description: 'List all recurring tasks in your workflow.', type: 'textarea', required: true },
      { name: 'Classification', description: 'For each task: Human-Led, AI-Led, or Centaur.', type: 'textarea', required: true },
      { name: 'Capability Assessment', description: 'For AI/Centaur tasks: what is the AI good at and where does it need help?', type: 'textarea', required: true },
      { name: 'Evolution Path', description: 'Which Human-Led tasks could become Centaur over time?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 1, prompt: 'Are you being conservative because you do not trust AI, or because the task genuinely requires human judgment? Those are different.' },
    ],
    doneSignal: 'Can you explain for every recurring task who does it (human, AI, or both) and why?',
    metricsSchema: [{ name: 'delegation_accuracy', unit: 'percentage', extraction: 'Correct delegation decisions' }],
    composabilityHooks: [
      { direction: 'receives_from', modeSlug: 'ai-onboarding', description: 'AI setup informs task delegation' },
      { direction: 'feeds_into', modeSlug: 'decision-protocol', description: 'Delegation map informs decision protocols' },
    ],
    timeEstimateMinutes: 25, sortOrder: 2,
  },
  {
    id: 'mode-decision-protocol', frameworkId: 'fw-synergy', slug: 'decision-protocol', name: 'Decision Protocol Mode',
    purpose: 'Define when AI leads decisions vs humans, override conditions, and retrospective cadence.',
    trigger: 'Use when AI is involved in decisions and you need clear rules about authority and override.',
    flowName: 'Govern',
    fieldsSchema: [
      { name: 'Decision Categories', description: 'List the types of decisions in your workflow.', type: 'textarea', required: true },
      { name: 'Authority Map', description: 'For each category: AI leads, Human leads, or Shared.', type: 'textarea', required: true },
      { name: 'Override Conditions', description: 'When can a human override an AI decision? When can AI override a human recommendation?', type: 'textarea', required: true },
      { name: 'Retrospective Cadence', description: 'How often do you review decision quality?', type: 'text', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Override conditions must be specific. "When it feels wrong" is not a condition. What data triggers an override?' },
    ],
    doneSignal: 'For any decision type, can you instantly say who has authority and what triggers an override?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'receives_from', modeSlug: 'centaur-assessment', description: 'Delegation map informs decision authority' }],
    timeEstimateMinutes: 15, sortOrder: 3,
  },
  {
    id: 'mode-verification-ritual', frameworkId: 'fw-synergy', slug: 'verification-ritual', name: 'Verification Ritual Mode',
    purpose: 'Build risk-scaled review protocols: high-stakes gets deep review, low-stakes flows free.',
    trigger: 'Use when AI output quality varies and you need consistent verification without slowing everything down.',
    flowName: 'Govern',
    fieldsSchema: [
      { name: 'Output Categories', description: 'List the types of AI output your team produces.', type: 'textarea', required: true },
      { name: 'Risk Level', description: 'For each category: High, Medium, or Low risk.', type: 'textarea', required: true },
      { name: 'Review Protocol', description: 'For each risk level: what review is required?', type: 'textarea', required: true },
      { name: 'Quality Threshold', description: 'What acceptance rate triggers a review of the protocol?', type: 'text', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Is your high-stakes review actually catching errors? When was the last time it found something significant?' },
    ],
    doneSignal: 'Can your team instantly classify any AI output by risk level and know the review protocol?',
    metricsSchema: [{ name: 'output_quality_score', unit: 'percentage', extraction: 'Acceptance rate from verification' }],
    composabilityHooks: [],
    timeEstimateMinutes: 15, sortOrder: 4,
  },
  {
    id: 'mode-knowledge-architecture', frameworkId: 'fw-synergy', slug: 'knowledge-architecture', name: 'Knowledge Architecture Mode',
    purpose: 'Structure persistent AI context so your AI colleague does not ask the same questions every session.',
    trigger: 'Use when AI keeps asking for context it should already have, or gives answers that ignore your business specifics.',
    flowName: 'Knowledge',
    fieldsSchema: [
      { name: 'Knowledge Domains', description: 'What categories of knowledge does the AI need?', type: 'textarea', required: true },
      { name: 'Persistent Context', description: 'For each domain: what should the AI always know?', type: 'textarea', required: true },
      { name: 'Update Triggers', description: 'When should each knowledge domain be updated?', type: 'textarea', required: true },
      { name: 'Access Pattern', description: 'How does the AI access this knowledge? Files, APIs, prompts?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 1, prompt: 'Is this everything the AI needs, or are you going to be disappointed next week when it does not know something you assumed it knew?' },
    ],
    doneSignal: 'Can your AI colleague start a new session and immediately have the context it needs to be useful?',
    metricsSchema: [],
    composabilityHooks: [{ direction: 'receives_from', modeSlug: 'information-architecture', description: 'Information structure feeds AI knowledge' }],
    timeEstimateMinutes: 20, sortOrder: 5,
  },
  {
    id: 'mode-trust-calibration', frameworkId: 'fw-synergy', slug: 'trust-calibration', name: 'Trust Calibration Mode',
    purpose: 'Set trust levels based on evidence, not feeling. Calibrate over-trust and under-trust.',
    trigger: 'Use when you suspect the team either trusts AI too much or too little, and decisions are being made on gut feel rather than data.',
    flowName: 'Trust',
    fieldsSchema: [
      { name: 'Trust Inventory', description: 'For each AI use case: current trust level (Over-trust, Calibrated, Under-trust, Untested).', type: 'textarea', required: true },
      { name: 'Evidence', description: 'What data supports each trust level?', type: 'textarea', required: true },
      { name: 'Calibration Actions', description: 'For over-trust: add verification. For under-trust: run a pilot.', type: 'textarea', required: true },
      { name: 'Review Schedule', description: 'When will you re-calibrate trust levels?', type: 'text', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 0, prompt: 'Over-trust is more dangerous than under-trust. When was the last time AI output was wrong and nobody caught it?' },
    ],
    doneSignal: 'Can you justify every trust level with evidence, not intuition?',
    metricsSchema: [{ name: 'override_rate', unit: 'percentage', extraction: 'Human overrides of AI decisions' }],
    composabilityHooks: [],
    timeEstimateMinutes: 15, sortOrder: 6,
  },
  {
    id: 'mode-ai-scaling', frameworkId: 'fw-synergy', slug: 'ai-scaling', name: 'AI Collaboration Scaling Mode',
    purpose: 'Plan how human-AI collaboration evolves as the organization grows.',
    trigger: 'Use when AI collaboration is working for one person or team and needs to scale to the organization.',
    flowName: 'Scale',
    fieldsSchema: [
      { name: 'Current State', description: 'How does AI collaboration work today? Who uses it, for what?', type: 'textarea', required: true },
      { name: 'Scaling Path', description: 'How should AI collaboration evolve? Solo → Team → Org.', type: 'textarea', required: true },
      { name: 'Standardization vs Customization', description: 'What should be standard across teams vs customized per team?', type: 'textarea', required: true },
      { name: 'Infrastructure Needs', description: 'What tools, access, or training is needed to scale?', type: 'textarea', required: true },
      { name: 'Risk Assessment', description: 'What could go wrong as you scale AI collaboration?', type: 'textarea', required: true },
    ],
    aiCoachPrompts: [
      { fieldIndex: 2, prompt: 'Too much standardization kills innovation. Too much customization creates chaos. Where is your line?' },
      { fieldIndex: 4, prompt: 'The biggest risk is usually not technical. It is cultural resistance. Who will resist and why?' },
    ],
    doneSignal: 'Can you present a roadmap for AI collaboration that any team lead can follow?',
    metricsSchema: [{ name: 'decision_accuracy_by_source', unit: 'score', extraction: 'Comparative outcomes: human vs AI vs centaur' }],
    composabilityHooks: [],
    timeEstimateMinutes: 25, sortOrder: 7,
  },
]

// ─── All Modes Combined ──────────────────────────────────────────────────────

export const modeSeeds: ModeInsert[] = [
  ...coreModes,
  ...airModes,
  ...maxModes,
  ...synergyModes,
]
