/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTeamsIndexRouteImport } from './routes/_auth/teams/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthProgressIndexRouteImport } from './routes/_auth/progress/index'
import { Route as AuthProgramsIndexRouteImport } from './routes/_auth/programs/index'
import { Route as AuthModesIndexRouteImport } from './routes/_auth/modes/index'
import { Route as AuthCoachIndexRouteImport } from './routes/_auth/coach/index'
import { Route as AuthAssessmentsIndexRouteImport } from './routes/_auth/assessments/index'
import { Route as AuthTeamsIdRouteImport } from './routes/_auth/teams/$id'
import { Route as AuthRunnerSessionIdRouteImport } from './routes/_auth/runner/$sessionId'
import { Route as AuthProgramsActiveRouteImport } from './routes/_auth/programs/active'
import { Route as AuthModesSlugRouteImport } from './routes/_auth/modes/$slug'
import { Route as AuthAssessmentsIdRouteImport } from './routes/_auth/assessments/$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamsIndexRoute = AuthTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProgressIndexRoute = AuthProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProgramsIndexRoute = AuthProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModesIndexRoute = AuthModesIndexRouteImport.update({
  id: '/modes/',
  path: '/modes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoachIndexRoute = AuthCoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssessmentsIndexRoute = AuthAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamsIdRoute = AuthTeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRunnerSessionIdRoute = AuthRunnerSessionIdRouteImport.update({
  id: '/runner/$sessionId',
  path: '/runner/$sessionId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProgramsActiveRoute = AuthProgramsActiveRouteImport.update({
  id: '/programs/active',
  path: '/programs/active',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModesSlugRoute = AuthModesSlugRouteImport.update({
  id: '/modes/$slug',
  path: '/modes/$slug',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssessmentsIdRoute = AuthAssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/assessments/$id': typeof AuthAssessmentsIdRoute
  '/modes/$slug': typeof AuthModesSlugRoute
  '/programs/active': typeof AuthProgramsActiveRoute
  '/runner/$sessionId': typeof AuthRunnerSessionIdRoute
  '/teams/$id': typeof AuthTeamsIdRoute
  '/assessments/': typeof AuthAssessmentsIndexRoute
  '/coach/': typeof AuthCoachIndexRoute
  '/modes/': typeof AuthModesIndexRoute
  '/programs/': typeof AuthProgramsIndexRoute
  '/progress/': typeof AuthProgressIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/teams/': typeof AuthTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/': typeof AuthIndexRoute
  '/assessments/$id': typeof AuthAssessmentsIdRoute
  '/modes/$slug': typeof AuthModesSlugRoute
  '/programs/active': typeof AuthProgramsActiveRoute
  '/runner/$sessionId': typeof AuthRunnerSessionIdRoute
  '/teams/$id': typeof AuthTeamsIdRoute
  '/assessments': typeof AuthAssessmentsIndexRoute
  '/coach': typeof AuthCoachIndexRoute
  '/modes': typeof AuthModesIndexRoute
  '/programs': typeof AuthProgramsIndexRoute
  '/progress': typeof AuthProgressIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/teams': typeof AuthTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/assessments/$id': typeof AuthAssessmentsIdRoute
  '/_auth/modes/$slug': typeof AuthModesSlugRoute
  '/_auth/programs/active': typeof AuthProgramsActiveRoute
  '/_auth/runner/$sessionId': typeof AuthRunnerSessionIdRoute
  '/_auth/teams/$id': typeof AuthTeamsIdRoute
  '/_auth/assessments/': typeof AuthAssessmentsIndexRoute
  '/_auth/coach/': typeof AuthCoachIndexRoute
  '/_auth/modes/': typeof AuthModesIndexRoute
  '/_auth/programs/': typeof AuthProgramsIndexRoute
  '/_auth/progress/': typeof AuthProgressIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/teams/': typeof AuthTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify'
    | '/assessments/$id'
    | '/modes/$slug'
    | '/programs/active'
    | '/runner/$sessionId'
    | '/teams/$id'
    | '/assessments/'
    | '/coach/'
    | '/modes/'
    | '/programs/'
    | '/progress/'
    | '/settings/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify'
    | '/'
    | '/assessments/$id'
    | '/modes/$slug'
    | '/programs/active'
    | '/runner/$sessionId'
    | '/teams/$id'
    | '/assessments'
    | '/coach'
    | '/modes'
    | '/programs'
    | '/progress'
    | '/settings'
    | '/teams'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/verify'
    | '/_auth/'
    | '/_auth/assessments/$id'
    | '/_auth/modes/$slug'
    | '/_auth/programs/active'
    | '/_auth/runner/$sessionId'
    | '/_auth/teams/$id'
    | '/_auth/assessments/'
    | '/_auth/coach/'
    | '/_auth/modes/'
    | '/_auth/programs/'
    | '/_auth/progress/'
    | '/_auth/settings/'
    | '/_auth/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teams/': {
      id: '/_auth/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthTeamsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/progress/': {
      id: '/_auth/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof AuthProgressIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/programs/': {
      id: '/_auth/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof AuthProgramsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modes/': {
      id: '/_auth/modes/'
      path: '/modes'
      fullPath: '/modes/'
      preLoaderRoute: typeof AuthModesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/coach/': {
      id: '/_auth/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthCoachIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assessments/': {
      id: '/_auth/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthAssessmentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teams/$id': {
      id: '/_auth/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof AuthTeamsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/runner/$sessionId': {
      id: '/_auth/runner/$sessionId'
      path: '/runner/$sessionId'
      fullPath: '/runner/$sessionId'
      preLoaderRoute: typeof AuthRunnerSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/programs/active': {
      id: '/_auth/programs/active'
      path: '/programs/active'
      fullPath: '/programs/active'
      preLoaderRoute: typeof AuthProgramsActiveRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modes/$slug': {
      id: '/_auth/modes/$slug'
      path: '/modes/$slug'
      fullPath: '/modes/$slug'
      preLoaderRoute: typeof AuthModesSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assessments/$id': {
      id: '/_auth/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AuthAssessmentsIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAssessmentsIdRoute: typeof AuthAssessmentsIdRoute
  AuthModesSlugRoute: typeof AuthModesSlugRoute
  AuthProgramsActiveRoute: typeof AuthProgramsActiveRoute
  AuthRunnerSessionIdRoute: typeof AuthRunnerSessionIdRoute
  AuthTeamsIdRoute: typeof AuthTeamsIdRoute
  AuthAssessmentsIndexRoute: typeof AuthAssessmentsIndexRoute
  AuthCoachIndexRoute: typeof AuthCoachIndexRoute
  AuthModesIndexRoute: typeof AuthModesIndexRoute
  AuthProgramsIndexRoute: typeof AuthProgramsIndexRoute
  AuthProgressIndexRoute: typeof AuthProgressIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthTeamsIndexRoute: typeof AuthTeamsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAssessmentsIdRoute: AuthAssessmentsIdRoute,
  AuthModesSlugRoute: AuthModesSlugRoute,
  AuthProgramsActiveRoute: AuthProgramsActiveRoute,
  AuthRunnerSessionIdRoute: AuthRunnerSessionIdRoute,
  AuthTeamsIdRoute: AuthTeamsIdRoute,
  AuthAssessmentsIndexRoute: AuthAssessmentsIndexRoute,
  AuthCoachIndexRoute: AuthCoachIndexRoute,
  AuthModesIndexRoute: AuthModesIndexRoute,
  AuthProgramsIndexRoute: AuthProgramsIndexRoute,
  AuthProgressIndexRoute: AuthProgressIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthTeamsIndexRoute: AuthTeamsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
