/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthModesIndexRouteImport } from './routes/_auth/modes/index'
import { Route as AuthCoachIndexRouteImport } from './routes/_auth/coach/index'
import { Route as AuthRunnerSessionIdRouteImport } from './routes/_auth/runner/$sessionId'
import { Route as AuthModesSlugRouteImport } from './routes/_auth/modes/$slug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModesIndexRoute = AuthModesIndexRouteImport.update({
  id: '/modes/',
  path: '/modes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoachIndexRoute = AuthCoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRunnerSessionIdRoute = AuthRunnerSessionIdRouteImport.update({
  id: '/runner/$sessionId',
  path: '/runner/$sessionId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModesSlugRoute = AuthModesSlugRouteImport.update({
  id: '/modes/$slug',
  path: '/modes/$slug',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/modes/$slug': typeof AuthModesSlugRoute
  '/runner/$sessionId': typeof AuthRunnerSessionIdRoute
  '/coach/': typeof AuthCoachIndexRoute
  '/modes/': typeof AuthModesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/': typeof AuthIndexRoute
  '/modes/$slug': typeof AuthModesSlugRoute
  '/runner/$sessionId': typeof AuthRunnerSessionIdRoute
  '/coach': typeof AuthCoachIndexRoute
  '/modes': typeof AuthModesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/modes/$slug': typeof AuthModesSlugRoute
  '/_auth/runner/$sessionId': typeof AuthRunnerSessionIdRoute
  '/_auth/coach/': typeof AuthCoachIndexRoute
  '/_auth/modes/': typeof AuthModesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify'
    | '/modes/$slug'
    | '/runner/$sessionId'
    | '/coach/'
    | '/modes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify'
    | '/'
    | '/modes/$slug'
    | '/runner/$sessionId'
    | '/coach'
    | '/modes'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/verify'
    | '/_auth/'
    | '/_auth/modes/$slug'
    | '/_auth/runner/$sessionId'
    | '/_auth/coach/'
    | '/_auth/modes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modes/': {
      id: '/_auth/modes/'
      path: '/modes'
      fullPath: '/modes/'
      preLoaderRoute: typeof AuthModesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/coach/': {
      id: '/_auth/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthCoachIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/runner/$sessionId': {
      id: '/_auth/runner/$sessionId'
      path: '/runner/$sessionId'
      fullPath: '/runner/$sessionId'
      preLoaderRoute: typeof AuthRunnerSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/modes/$slug': {
      id: '/_auth/modes/$slug'
      path: '/modes/$slug'
      fullPath: '/modes/$slug'
      preLoaderRoute: typeof AuthModesSlugRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthModesSlugRoute: typeof AuthModesSlugRoute
  AuthRunnerSessionIdRoute: typeof AuthRunnerSessionIdRoute
  AuthCoachIndexRoute: typeof AuthCoachIndexRoute
  AuthModesIndexRoute: typeof AuthModesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthModesSlugRoute: AuthModesSlugRoute,
  AuthRunnerSessionIdRoute: AuthRunnerSessionIdRoute,
  AuthCoachIndexRoute: AuthCoachIndexRoute,
  AuthModesIndexRoute: AuthModesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
